Redirect to alias for deleted facilities
open-apparel-registry/open-apparel-registry pull request #1473
Opened 2021-09-23 15:45 UTC by TaiWilkin

## Overview

If a user attempts to access a facility which has been deleted, is some cases the facility might have been moved to a new OAR ID or might have been deleted because it was a duplicate of a different facility, and users should be rerouted to the correct facility. When a facility is not found, determines if any aliases exist for the given OAR ID, then redirects to the first alias found, only returning a 404 if no aliases exist. 

Connects #XXX

## Demo

![Sep-23-2021 11-41-22](https://user-images.githubusercontent.com/21046714/134539406-e38a5822-e79c-4766-bb88-2e8b06912484.gif)

## Notes

Redirects sent by servers are handled automatically by the browser, without giving the clientside app access to interfere in the process. Specifically, the browser receives the redirect and sends a GET request to the API for the alias facility - sending a request to the server for the desired frontend URL causes an error, since the API can't handle the request - eg the 302 is in response to the request for data, so the redirect must result in the app returning the correct data, not in the app returning a different webpage. Although redirecting to request the alias facility data correctly returns the desired facility, we then have a mismatch between the URL OAR ID and the actual displayed facility. 

The most common instance of this situation I found online was wanting to redirect unauthorized users to a login page. The suggested method was to send a 401 response instead of a 302, in order to allow the app to handle redirecting to the login page. However, a 401 response in our situation would be inaccurate. 

Instead, what we needed was two redirects - one to redirect to fetch the correct data, and one to redirect to the correct webpage. In order to manage this, we check in the facility details component to see if the provided OAR ID and the returned data id match. If there is a mismatch, we return a redirect to go to the appropriate URL. Because we check on component mount if the data is already loaded for the provided OAR ID parameter, this doesn't cause a second fetch of the data. Syntactically, this makes sense (we are in fact making two separate redirected requests - for the data and for the page), and experientially it looks to the user as if the page has loaded as usual without any disruption. 

## Testing Instructions

* Run `./scripts/server`. Get the URL for a facility details page. Create a FacilityAlias for the facility, and then delete the facility. 
* Attempt to access the URL for the facility details page of the deleted facility. You should be redirected to the facility alias' details page. 

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

2021-09-27 19:28 UTC, jwalgran requested changes
To test I used this query to find facilities with multiple matches

```sql
select facility_id, count(*) 
from api_facilitymatch 
group by facility_id 
order by count(*) desc;
```

I then deleted a facility with multiple matches and verified that a `FacilityAlias` row was created.

After applying this change

```diff
diff --git a/src/django/api/views.py b/src/django/api/views.py
index eb411cf..951e3a3 100644
--- a/src/django/api/views.py
+++ b/src/django/api/views.py
@@ -885,7 +885,7 @@ class FacilitiesViewSet(mixins.ListModelMixin,
         except Facility.DoesNotExist:
             # If the facility is not found but an alias is available,
             # redirect to the alias
-            aliases = FacilityAlias.objects.filter(oar_id='CN20212562SA17G')
+            aliases = FacilityAlias.objects.filter(oar_id=pk)
             if len(aliases) == 0:
                 raise NotFound()
             oar_id = aliases.first().facility.id

```

I verified that browsing the old redirected properly.

2021-09-28 13:37 UTC, TaiWilkin commented on src/django/api/views.py
> +            aliases = FacilityAlias.objects.filter(oar_id='CN20212562SA17G')
Oh my - thank you for catching that. It's been fixed in b0e9bab.

2021-09-29 14:06 UTC, jwalgran reviewed
👍

2021-09-29 14:06 UTC, jwalgran approved these changes

2021-09-29 15:04 UTC, merged