Update final facility_type/processing_type taxonomy
open-apparel-registry/open-apparel-registry pull request #1644
Opened 2022-02-11 21:02 UTC by emilyhu0106

## Overview

Update the constant list of facility_type/production_type taxonomy according to the final version in Feb 9th. This is an updated version of #1601 

Connects #1634

## Note

Some of the terms were deleted after the #1601, I am not sure if we should delete them all together, so those lines are commented out for now.

## Testing Instructions

* Review the [taxonomy](https://docs.google.com/spreadsheets/d/1HlGoYgj0rbtxnhgm0LAWk5lgFCSw3A2V/edit#gid=299419561) and suggest any differences in the constants.

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

2022-02-11 21:03 UTC, emilyhu0106 commented
@caseycesari Do we need any additional tests here to verify the changes?

2022-02-14 16:41 UTC, caseycesari requested changes
This looks good, but I think we should the commented out entries.

2022-02-15 18:29 UTC, caseycesari approved these changes
Good to go!

2022-02-15 21:12 UTC, emilyhu0106 commented
Thank you for reviewing!

2022-02-15 22:55 UTC, merged