Filter facilities by sectors
open-apparel-registry/open-apparel-registry pull request #1930
Opened 2022-06-22 05:46 UTC by emilyhu0106

## Overview

Allow users to filter facilities by the `sectors` in Swagger and front-end. We capitalize the first letter of each query value to match the stored value, then any facilities which have any matching sector are returned.

Connects #1832 

## Demo

In Swagger:
![image](https://user-images.githubusercontent.com/60887686/174924365-3c0a5eb5-4d6e-4fc0-afd9-a392a25e3e50.png)

In front-end:
![2022-06-21 18 34 36](https://user-images.githubusercontent.com/60887686/174924481-b2e29da6-4596-4f19-aa85-c8349db12898.gif)

## Note

`sector` is used as the title in the facility filter and detail sidebar, but here we use `sectors` as the parameter name to match the name in variable name returned from the facility detail API.

## Testing Instructions

* Check out this branch and run `./scripts/server`
* Log in as `c3@example.com, contribute and fully process the list [ExtendedFieldsTestListLimited - Sector.csv](https://github.com/open-apparel-registry/open-apparel-registry/files/8954699/ExtendedFieldsTestListLimited.-.Sector.csv)
* To test in back-end: Go to [Swagger](http://localhost:8081/api/docs/#!/facilities/facilities_list), add `sectors` param (including upper- and lower- cases)
    - [ ] Make sure the returned facilities are in valid sectors
* To test in front-end: go to main page, choose sectors based on the choices (new sectors choices should be added automatically as implemented in #1899), and click "Search"
    - [ ] Make sure the returned facilities are in valid sectors

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

2022-06-22 13:38 UTC, maurizi reviewed
Left some suggestions to fix the lint tripping up CI

2022-06-22 13:38 UTC, maurizi commented on src/django/api/models.py
> +from cmath import log
```suggestion
```

2022-06-22 13:38 UTC, maurizi commented on src/django/api/tests.py
> +class SectorAPITest(FacilityAPITestCaseBase):
```suggestion

class SectorAPITest(FacilityAPITestCaseBase):
```

2022-06-22 13:38 UTC, maurizi commented on src/django/api/tests.py
> +            'sector': ['Apparel','Beauty']
```suggestion
            'sector': ['Apparel', 'Beauty']
```

2022-06-22 13:46 UTC, maurizi commented
> `sector` is used as the title in the facility filter and detail sidebar, but here we use `sectors` as the parameter name to match the name in variable name returned from the facility detail API.

All of the other parameter names in the API follow this same pattern, so I think this is fine 😄

2022-06-22 14:55 UTC, maurizi requested changes

2022-06-22 15:25 UTC, emilyhu0106 commented on src/django/api/models.py
> +            )
I was thinking that capitalizing could help with the swagger users, since there's no options there. @jwalgran What's your suggestions?

2022-06-22 21:39 UTC, jwalgran commented on src/django/api/models.py
> +            )
I think that we should skip capitalization here for two reasons:
- The we call `strip` and `title` on the values that are indexed, so `capitalize` would not match in all cases. It is better to have the value processing happing in a single place, if possible.
- API users can request "valid" search values by making a `GET /api/sectors` request

To help swagger users I would recommend adding a new schema field to `FacilitiesAPIFilterBackend` and in the `description` property explain that "Values must match those returned from the GET /api/sectors endpoint." https://github.com/open-apparel-registry/open-apparel-registry/blob/b171608071e84af321d1f2705b344aac49f9a228/src/django/api/views.py#L692

2022-06-23 16:23 UTC, maurizi approved these changes
👍

2022-06-23 17:48 UTC, merged