Update moderation UI to trigger batch processing
open-apparel-registry/open-apparel-registry pull request #2048
Opened 2022-08-15 21:07 UTC by maurizi

## Overview

Implements the backend for the stubs added in #2044 to approve/reject lists

Connects #2018 

## Demo

![approve](https://user-images.githubusercontent.com/4432106/184717997-38f6085e-8b59-4b4c-95cd-f9fb685dde0d.gif)

## Testing Instructions

* `scripts/server`
* Add a new new, and note it's ID
  * Log in as a superuser and go to the detail page for this list - you should _not_ see approve / reject buttons
* Use ` ./scripts/manage batch_process --list-id 16 --action parse` to run the first part of batch processing
  * You should now see approve / reject buttons for the list above
* You should be able to update the status dropdown to approved / rejected on the admin list dashboard to see your list(s) after approving / rejecting it
* Rejecting a list should print an email in the console

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

2022-08-16 23:17 UTC, jwalgran requested changes
The core functionality is working and is clearly implemented.

I commend on some email fixups that need to be made.

I also noticed that if the list is rejected we were still showing a "this list is being processed" on the list detail page since the individual items were still (and will be forever) in a PARSED status. 


Here is a potential solution to avoiding this potentially confusing message.

```diff
diff --git a/src/app/src/components/FacilityListItemsTable.jsx b/src/app/src/components/FacilityListItemsTable.jsx
index a0788c5c..7f51e4b5 100644
--- a/src/app/src/components/FacilityListItemsTable.jsx
+++ b/src/app/src/components/FacilityListItemsTable.jsx
@@ -50,7 +50,9 @@ import {
     rowsPerPageOptions,
     facilityListItemStatusChoicesEnum,
     facilityListItemErrorStatuses,
+    facilityListStatusChoicesEnum,
     facilityListStatusFilterChoices,
+    facilityListSummaryStatusMessages,
     matchResponsibilityEnum,
 } from '../util/constants';
 
@@ -346,7 +348,9 @@ class FacilityListItemsTable extends Component {
                     md={6}
                     style={facilityListItemsTableStyles.summaryStatusStyles}
                 >
-                    {makeFacilityListSummaryStatus(list.statuses)}
+                    {list.status !== facilityListStatusChoicesEnum.REJECTED
+                        ? makeFacilityListSummaryStatus(list.statuses)
+                        : facilityListSummaryStatusMessages.REJECTED}
                 </Grid>
                 <Grid item sm={12} md={6}>
                     <TablePagination
diff --git a/src/app/src/util/constants.js b/src/app/src/util/constants.js
index fed4613d..aaff8969 100644
--- a/src/app/src/util/constants.js
+++ b/src/app/src/util/constants.js
@@ -443,6 +443,7 @@ export const facilityListSummaryStatusMessages = Object.freeze({
     AWAITING: 'Some potential matches require your feedback.',
     PROCESSING: 'The list is still being processed.',
     COMPLETED: 'This list has been processed successfully.',
+    REJECTED: 'This list was rejected and with not be processed.',
 });
 
 export const DEFAULT_PAGE = 1;

```

2022-08-17 16:13 UTC, maurizi commented on src/django/api/mail.py
> +        'facility_list_url': make_facility_list_url(request, facility_list),
Fixed in https://github.com/open-apparel-registry/open-apparel-registry/pull/2048/commits/120440c89680925a94d1d0718c22621116266256

2022-08-17 16:13 UTC, maurizi commented on src/django/api/templates/mail/facility_list_rejection_body.txt
> +- Facility list URL: <a href="{{ facility_list_url }}">{{ facility_list_url }}</a>
Fixed in https://github.com/open-apparel-registry/open-apparel-registry/pull/2048/commits/120440c89680925a94d1d0718c22621116266256

2022-08-17 18:25 UTC, jwalgran approved these changes
Fixups look good. Thanks.

2022-08-17 19:58 UTC, merged