Search/Filtering/Results UX Updates (#2049)
open-apparel-registry/open-apparel-registry pull request #2110
Opened 2022-08-30 21:51 UTC by jacobscarfmerrell

## Overview

Brief description of what this PR does, and why it is needed.

Connects #2049 

## Demo

Optional. Screenshots, `curl` examples, etc.

## Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

2022-09-06 17:24 UTC, jwalgran commented
The build failure was caused by lint

```
./api/serializers.py:612:80: E501 line too long (81 > 79 characters)
```

2022-09-07 15:55 UTC, TaiWilkin requested changes
This is a great framework for the new layout. Thanks for working through this!
Let's hold off on trying to fix the map error when resizing, based on time constraints and since it doesn't seem to impact functionality. Please make a follow-up ticket for fixing the error when time allowed, though. 
Some styling adjustment requests:
- Can you update the top-of-list buttons (download, copy, filter, etc) to have the updated style, and add some space between the tabs and the filter button? (If updating the tab style turns out to be complicated/time-consuming, please instead make a follow-up card for that.)
- In the same region, can you add the 'Facilities' header and facilities count (count should be available in Redux)? (Don't add the 'sort' dropdown though)
<img width="172" alt="Screen Shot 2022-09-07 at 11 31 44 AM" src="https://user-images.githubusercontent.com/21046714/188920057-e741332e-a1e4-44d1-afe6-d6eb84347356.png">
- Can you make the facility results panel slightly wider (maybe move to 4 columns instead of 3)?
- Can you vertically center the items in the OAR ID/Claimed row so the claim badge is aligned a bit more? 
<img width="342" alt="Screen Shot 2022-09-07 at 10 44 45 AM" src="https://user-images.githubusercontent.com/21046714/188920524-35da8fbf-cecd-4141-81b7-4f00a03dfc2c.png"> vs <img width="253" alt="Screen Shot 2022-09-07 at 11 40 25 AM" src="https://user-images.githubusercontent.com/21046714/188920661-2a9fb329-fc5e-43fc-8a3d-531d4760c6d4.png">
- Can you update the multiple-selected-contributors style to the new toggle with the 'i' next to the label? (OR if this turns out to be time-consuming, just adjusting the styling so the 'i' button doesn't overflow to a new line)
<img width="227" alt="Screen Shot 2022-09-07 at 11 41 39 AM" src="https://user-images.githubusercontent.com/21046714/188921236-59910cbf-d80f-453d-ae59-9d7cdbee6847.png"> vs 
<img width="136" alt="Screen Shot 2022-09-07 at 11 41 28 AM" src="https://user-images.githubusercontent.com/21046714/188921277-9ae3ad81-54f5-4aa2-a8e2-853b6c95e080.png">
- Can you add a close button and 'Filters' header to the filters drawer? 
<img width="170" alt="Screen Shot 2022-09-07 at 11 44 30 AM" src="https://user-images.githubusercontent.com/21046714/188921629-d6974602-a6f8-438e-91fa-08a86c13864f.png">

2022-09-07 15:57 UTC, TaiWilkin commented on src/app/src/components/MapAndSidebar.jsx
> +function mapStateToProps({ ui: { activeFilterSidebarTab } }) {
Looks like this prop isn't being used, so this mapStateToProps can probably be removed

2022-09-07 16:05 UTC, TaiWilkin commented on src/app/src/components/FilterSidebar.jsx
> +                    <Grid item sm={12} md={3}>
Can we increase this to `md={4}`?

2022-09-07 16:25 UTC, jwalgran commented
During our weekly check-in with the OS Hub team I showed a preview of this branch and they were concerned about the relative widths of the 3 columns (the search fields section looked a bit narrow). Tai's specific review comments may address this. Thanks.

2022-09-09 14:05 UTC, jacobscarfmerrell commented
@TaiWilkin @jwalgran I think all that's left to do is to update the multiple-selected-contributors style to the new toggle with the 'i' next to the label and to try and boost the size of the filter bank on large screens. I can finish these two points tomorrow morning!

2022-09-09 17:10 UTC, TaiWilkin commented
@jacobscarfmerrell Great work on the tab and styling! They look great. This is coming along well. 

I'm seeing a couple of small issues still. 

- I think the new styling on the contributors tab caused this - it's now pushed out of alignment on the homepage. 
<img width="633" alt="Screen Shot 2022-09-09 at 1 05 55 PM" src="https://user-images.githubusercontent.com/21046714/189405772-87ad3d4b-42aa-4ec0-aaf0-646d6a852320.png">
- We should include the Facilities header and count (for the results panel) on the desktop / non-mobile view as well
- This one is weird, so I made a gif - when I'm scrolling down the list, the padding changes:
![PaddingGlitch](https://user-images.githubusercontent.com/21046714/189406117-7436ce76-1b38-4e19-8e77-49a2d22e7319.gif)
- On the desktop view, the last item on the results list is blocked by the footer

2022-09-14 12:46 UTC, TaiWilkin commented
@jwalgran This PR is ready to show to Mariel and team at the demo today.

2022-09-14 16:39 UTC, TaiWilkin approved these changes
Thank you for working through this complex issue!

2022-09-16 13:59 UTC, merged