Store raw data
open-apparel-registry/open-apparel-registry pull request #2154
Opened 2022-09-20 15:47 UTC by TaiWilkin

## Overview

Brief description of what this PR does, and why it is needed.

Connects #XXX

## Demo

Optional. Screenshots, `curl` examples, etc.

## Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

2022-09-21 13:30 UTC, TaiWilkin commented
@jwalgran I haven't built a test branch for this. Do we want to apply this to OAR as well as OSHub? If so, should we do an OAR test branch, so we get it running on a less user-facing environment before we merge to ogr/develop and develop?

2022-09-21 20:21 UTC, jwalgran commented
We don't need to make these changes to OAR. I recommend that we coordinate with the OS Hub team when we will be testing this on OS Hub staging

2022-09-21 21:55 UTC, jwalgran requested changes
Nice, clear implementation. Thanks for the easy-to-follow commit sequence. I was able to successfully test this locally.

I commented on one terraform error I uncovered when trying to run `plan` and I pushed up  aae665a5 with suggested terraform updates to ensure that we set the env var for all Django process. If you like that implementation you can cherry-pick the commit onto the PR branch.

2022-09-21 21:55 UTC, jwalgran commented on deployment/terraform/iam.tf
> +  role   = aws_iam_role.ecs_task_role.name
When I ran `scripts/infra plan` in a terraform container I got an error on this line. Looking at the other policies in the file, I think we need to use `app_task_role`

```suggestion
  role   = aws_iam_role.app_task_role.name
```

2022-09-22 19:20 UTC, TaiWilkin commented
@jwalgran Ready for another look!

2022-09-22 20:34 UTC, jwalgran approved these changes
Retested locally. Terraform `plan` runs without error. Looks good. I made one small text-change  suggestion that I noticed in my re-review.

2022-09-22 20:34 UTC, jwalgran commented on src/app/src/components/FacilityListItems.jsx
> +                Download Formatted CSV
Not directly related to the new functionality, but since we accept and encourage using Excel files we should consider changing "CSV" here to "File"

2022-09-23 16:51 UTC, merged